# Generated by Django 3.0.5 on 2020-05-28 11:29

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(default='https://cdn.zeplin.io/5d0afc9102b7fa56760995cc/assets/05bab6ee-6f73-4e37-b727-179336e41690.svg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('travel_date_time', models.DateTimeField(null=True)),
                ('flexible_timings', models.BooleanField(default=False)),
                ('flexible_from_date_time', models.DateTimeField(null=True)),
                ('flexible_to_date_time', models.DateTimeField(null=True)),
                ('travel_medium', models.CharField(choices=[('BUS', 'BUS'), ('TRAIN', 'TRAIN'), ('FLIGHT', 'FLIGHT')], max_length=50)),
                ('asset_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('travel_date_time', models.DateTimeField(null=True)),
                ('flexible_timings', models.BooleanField(default=False)),
                ('flexible_from_date_time', models.DateTimeField(null=True)),
                ('flexible_to_date_time', models.DateTimeField(null=True)),
                ('seats', models.IntegerField()),
                ('asset_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('travel_date_time', models.DateTimeField(null=True)),
                ('flexible_timings', models.BooleanField(default=False)),
                ('flexible_from_date_time', models.DateTimeField(null=True)),
                ('flexible_to_date_time', models.DateTimeField(null=True)),
                ('seats', models.IntegerField()),
                ('laguage_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date_time', models.DateTimeField(null=True)),
                ('flexible_timings', models.BooleanField(default=False)),
                ('flexible_from_date_time', models.DateTimeField(null=True)),
                ('flexible_to_date_time', models.DateTimeField(null=True)),
                ('asset_quantity', models.IntegerField()),
                ('asset_type', models.CharField(choices=[('BAG', 'BAG'), ('LAPTOP', 'LAPTOP'), ('DOCUMENTS', 'DOCUMENTS'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('asset_type_others', models.CharField(max_length=100, null=True)),
                ('asset_sensitivity', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM')], max_length=50)),
                ('deliver_to', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
