# Generated by Django 3.0.5 on 2020-07-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetrequest',
            old_name='accepted_by',
            new_name='accepted_by_id',
        ),
    ]
