# Generated by Django 3.0.5 on 2020-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0002_auto_20200528_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='accepted_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='acceptes_person_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('CONFIRM', 'CONFIRM'), ('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='accepted_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='acceptes_person_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('CONFIRM', 'CONFIRM'), ('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
