# Generated by Django 3.0.5 on 2020-05-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0003_auto_20200529_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='accepted_person',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='acceptes_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='accepted_person',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='acceptes_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='status',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
