# Generated by Django 3.0.5 on 2020-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0005_auto_20200604_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_type_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
