# Generated by Django 3.0.5 on 2020-06-22 14:42

from django.db import migrations, models
import lets_ride.models.ride_request


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0007_auto_20200606_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='seats',
            field=models.IntegerField(validators=[lets_ride.models.ride_request.validate_seats]),
        ),
    ]
