# Generated by Django 3.0.5 on 2020-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0010_user2_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(to='lets_ride.Group')),
            ],
        ),
    ]
