# Generated by Django 3.0.5 on 2020-06-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0011_group1_user3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user3',
            name='groups',
            field=models.ManyToManyField(to='lets_ride.Group1'),
        ),
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lets_ride.Group4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lets_ride.User4')),
            ],
        ),
        migrations.AddField(
            model_name='group4',
            name='members',
            field=models.ManyToManyField(through='lets_ride.GroupLevel', to='lets_ride.User4'),
        ),
    ]
